# Application Name and Version
Application = "GLOBAL.CICD.ReactApp"
Application_Version = "1.0.0"

# Component info
Name = "GLOBAL.CICD.ReactWebApp"
Variant = "${GIT_BRANCH}"
Version = "v1.0.${BUILD_NUM}-g${SHORT_SHA}"

[Attributes]
    ServiceOwner = "${DHUSER}"
    ServiceOwnerEmail = "you@example.com"